config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  get 'my_portfolio', to: 'users#my_portfolio'
  devise_for :users 
  root 'welcome#index'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendship, only: [:create, :destroy]
  resources :users, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def self.primary_class
    true
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/models/stock.rb
require 'finnhub_ruby'

class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users , through: :user_stocks

    validates :name, :ticker, presence: true
    def self.new_lookup(ticker_symbol)
        FinnhubRuby.configure do |config|
            config.api_key['api_key'] = Rails.application.credentials.iex_client[:finnhub_api_key]
        end       

        client = FinnhubRuby::DefaultApi.new
        
        begin
            new(ticker: ticker_symbol,name: client.company_profile2({symbol: ticker_symbol}).name, last_price: client.quote(ticker_symbol).c)
        rescue => exception
            return nil
        end
    end
    
    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks , through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where( id: stock.id ).exists?

  end


  def under_count_limit
    stocks.count < 10
  end


  def can_track_stock?(ticker_symbol)
    under_count_limit && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_search(param) + last_name_search(param) + email_search(param)).uniq
    return nil unless to_send_back
    to_send_back
  end


  def self.first_name_search(param)
    decide_field_name("first_name",param)
  end
  
  def self.last_name_search(param)
    decide_field_name("last_name",param)
  end

  def self.email_search(param)
    decide_field_name("email",param)
  end
  
  def self.decide_field_name(field_name,param)
    where("#{field_name} like ?","%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    !self.friends.where(id: friend_id ).exists?
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
    
end

app/controllers/friendship_controller.rb
class FriendshipController < ApplicationController
    
    def create
        friendship = Friendship.create(user_id: params[:user_id], friend_id: params[:friend_id])
        if friendship.save
            friend = User.find(params[:friend_id]).full_name
            flash[:notice]="Following #{friend}"
        else
            flash[:alert]="Something went wrong"
        end
        redirect_to my_friends_path
    end
    
    def destroy
        friend = User.find(params[:id])
        friendship= Friendship.where(user_id: current_user.id, friend_id: friend.id).first
        friendship.destroy
        flash[:notice]="Unfollowed #{friend.full_name} "
        redirect_to my_friends_path
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    
    def search
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                respond_to do |format|
                    format.js {render partial: 'users/result'}
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Please enter a valid symbol"
                    format.js {render partial: 'users/result'}
                end
            end
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter a symbol to search"
                format.js {render partial: 'users/result'}
            end
        end
    end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save
        end
        
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice]= "#{stock.name} successfully added to your portfolio"
        redirect_to my_portfolio_path
    end
    def destroy
        stock =Stock.find(params[:id])
        user_stock= UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        user_stock.destroy
        flash[:notice]="#{stock.name} successfully destroyed"
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user= current_user
      @user_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end

  def search
    if params[:friend_name].present?
      @friends = User.search(params[:friend_name])
      @friends = current_user.except_current_user(@friends)
      if @friends
          respond_to do |format|
              format.js {render partial: 'users/friend_result'}
          end
      else
          respond_to do |format|
              flash.now[:alert] = "Couldn't find the user"
              format.js {render partial: 'users/friend_result'}
          end
      end

    else
      respond_to do |format|
          flash.now[:alert] = "Please enter a valid name or email to search"
          format.js {render partial: 'users/friend_result'}
      end
    end
  end
end

app/controllers/welcome_controller.rb
require 'faraday'
require 'json'

class WelcomeController < ApplicationController
    def index
        # connection=Faraday.new('https://api.tiingo.com/tiingo/daily/AAPL/prices?startDate=2012-01-03&endDate=2014-01-03&token=https://api.tiingo.com/tiingo/daily/AAPL/prices?startDate=2012-01-03&endDate=2014-01-03&token=d61c1c8f74de5f972428979c8738b73ec3cf6b02')
        response = Faraday.get 'https://api.tiingo.com/tiingo/daily/all/prices?startDate=2012-01-03&endDate=2014-01-03&token=https://api.tiingo.com/tiingo/daily/AAPL/prices?startDate=2012-01-03&endDate=2014-01-03&token=d61c1c8f74de5f972428979c8738b73ec3cf6b02'
        response = JSON.parse(response.body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class= "row mt-3" >
    <div class= "col-md-9">
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th scope="col">Email</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @friends.each do |friend|%>
                <tr>
                    <th scope="row"><%= friend.email%></th>
                    <td><%= friend.first_name%></td>
                    <td><%= friend.last_name%></td>
                    <td><%= link_to "Unfollow", friendship_path(friend.id), method: :delete, class:"btn btn-sm btn-warning", data: {confirm: "Are you sure?"} %>
                        <%= link_to "View Profile", user_path(friend.id) ,class: "btn btn-sm btn-success mx-1" , method: :get%>

                    </td>
                </tr>
            <%end%>
        </tbody>
        </table>
    </div>
</div>

app/views/layouts/_message.html.erb
<% if notice %>
    <div class="alert alert-success alert-dismissible fade show my-2" role="alert">
        <strong> <%= notice %></strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

<% if alert %>
    <div class="alert alert-danger alert-dismissible fade show my-2" role="alert">
        <strong> <%= alert %></strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container">
        <%= link_to "Finance Tracker", root_path, class:"navbar-brand" %>
        <% if current_user%>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item <%= 'active' if request.path == my_portfolio_path%> ">
                <%= link_to "My Portfolio", my_portfolio_path, class:"nav-link"%>
              </li>
              <li class="nav-item <%= 'active' if request.path == my_friends_path%>">
                <%= link_to "My Friends", my_friends_path, class:"nav-link"%>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Edit user", edit_user_registration_path , class: "dropdown-item" %>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                </ul>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto" >
              <li class="nav-item m-2">
                <%= current_user.full_name%>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, class: "btn btn-danger mx-1", method: :delete  %>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        <%end%>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    
    <%= javascript_include_tag :jquery, :jquery_ujs %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>

    <div class="container">
      <%= render 'layouts/message' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class= "row mt-3" >
    <div class= "col-md-9">
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @user_stocks.each do |stock|%>
                <tr>
                    <th scope="row"><%= stock.ticker%></th>
                    <td><%= stock.name%></td>
                    <td><%= stock.last_price%></td>
                    <td>
                        <% if current_user.can_track_stock?(stock.ticker) %>
                            <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: stock.ticker),class: "btn btn-sm btn-success mx-1" , method: :post%>
                        <% elsif current_user.id != @user.id %>
                            <span class="Label mx-2">
                                You are already tracking
                                <% if !current_user.under_count_limit %>
                                10 stocks
                                <% end %>
                                <% if current_user.stock_already_tracked?(stock.ticker) %>
                                this stock
                                <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
                                                                                class: 'btn btn-sm btn-warning' %>

                                <% end %>
                            </span>
                        <% end %>
                        <% if current_user.id == @user.id %>
                            <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
                                                    class: 'btn btn-sm btn-warning' %>
                        <% end %>

                    </td>
                </tr>
            <%end%>
        </tbody>
        </table>
    </div>
</div>

app/views/users/_friend_result.html.erb
<%= render 'layouts/message' %>

<% if @friends %>
    <div class="row mt-3">
        <div class="col-md-9">
            <div class="card ">
                <% @friends.each do |friend| %>
                    <div class="card-body">
                        <strong>Name: </strong><%= friend.full_name%>
                        <strong>Email: </strong><%= friend.email%>
                        <%= link_to "View Profile", user_path(friend.id) ,class: "btn btn-sm btn-success" , method: :get%>
                        <%if current_user.not_friends_with?(friend.id)%>
                            <%= link_to "Follow", friendship_index_path(user_id: current_user.id, friend_id: friend.id ),class: "btn btn-sm btn-success" , method: :post%>
                        <% else %>
                            <%= link_to "Unfollow", friendship_path(friend.id), method: :delete, class:"btn btn-sm btn-warning", data: {confirm: "Are you sure?"} %>
                        <%end%>
                    </div>
                <%end%>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#results').innerHTML= '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<%= render 'layouts/message' %>
<% if @stock %>
    <div class="row mt-3">
        <div class="col-md-9">
            <div class="card ">
                <div class="card-body">
                    <strong>Ticker Symbol: </strong><%= @stock.ticker %>
                    <strong>Name: </strong><%= @stock.name%>
                    <strong>Price: </strong><%= @stock.last_price%>
                
                    <% if current_user.can_track_stock?(@stock.ticker) %>
                        <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker),class: "btn btn-success " , method: :post%>
                    <% else%>
                        <span class="Label mx-2"><b>
                            You are already tracking
                            <% if !current_user.under_count_limit %>
                                10 stocks
                            <%end%>
                            <% if current_user.stock_already_tracked?(@stock.ticker) %>
                                this stock 
                            <%end%></b>
                        </span>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML= '<%= j render 'users/result.html' %>'

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class="search-aria mt-5">
    <h3>Search Friends</h3>
    <%= form_tag search_friend_path, remote: true, method: :get  do%>
        <div class="form-group row">
            <div class="col-md-9 no-right-padding">
                <%= text_field_tag :friend_name, params[:friend_name], placeholder: "Search friends", autofocus: true, class: 'form-control form-control'%>
            </div>
            <div class="col-md-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do%>
                    <%= 'Search'%>
                <%end%>
            </div>
        </div>
    <%end%>
</div>

<div id = "results">
</div>

<% if !@friends.empty?%>
    <%= render 'friends/list' %>
<%end%>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-aria mt-5">
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, remote: true, method: :get  do%>
        <div class="form-group row">
            <div class="col-md-9 no-right-padding">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock Ticker Symbol", autofocus: true, class: 'form-control form-control'%>
            </div>
            <div class="col-md-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do%>
                    <%= 'Search'%>
                <%end%>
            </div>
        </div>
    <%end%>
</div>

<div id = "results">
</div>

app/views/users/show.html.erb
<h1> User Details </h1>

<div class="row mt-3">
    <div class="col-md-9">
        <div class="card ">
                <div class="card-body">
                    <strong>Name: </strong><%= @user.full_name%>
                    <strong>Email: </strong><%= @user.email%>
                    <%if current_user.not_friends_with?(@user.id)%>
                        <%= link_to "Follow", friendship_index_path(user_id: current_user.id, friend_id: @user.id ),class: "btn btn-sm btn-success" , method: :post%>
                    <% else %>
                        <%= link_to "Unfollow", friendship_path(@user.id), method: :delete, class:"btn btn-sm btn-warning", data: {confirm: "Are you sure?"} %>
                    <%end%>
                </div>
        </div>
    </div>
</div>


<% if !@user_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else%>
    <p class="mt-3"> <b><em>THIS USER IS NOT TRACKING ANY STOCKS <em> :(<b></p>
<%end%>

app/views/welcome/index.html.erb
<h1>This is the welcome page of The Finance Tracker app</h1>